### GET request to example server
POST http://localhost:3000/api/identify/signin
Content-Type: application/json

{
  "email": "heavycream9090@icloud.com",
  "password": "Rt3$YiOO"
}

###
POST http://localhost:3000/api/refresh
Content-Type: application/json
Cookie: __rclientid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNzc3OTI3MSwiaWF0IjoxNzI3NzM2MDcxLCJqdGkiOiJkM2JkNjg2MWFmOTA0N2ZjOWFiZWU3MjU3ZjI1MDFmZiIsInVzZXJpZCI6IllXbzhudUplcHZaQ3hoaDYiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJoZWF2eWNyZWFtOTA5MEBpY2xvdWQuY29tIiwib3JpZ19pYXQiOjE3Mjc3MzYwNzEsIm90cF9kZXZpY2VfaWQiOm51bGx9.R5fWlKaKcAyncGfDsOatXcMgyhUkryX2Wdgy2oNcOrI