# Generated by Django 5.1.1 on 2024-10-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='is_oauth_user',
            field=models.BooleanField(default=False),
        ),
    ]
