# Generated by Django 5.1.2 on 2024-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_walletuser_is_oauth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='provider',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
