# Generated by Django 5.1.2 on 2024-11-29 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_walletuser_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='device_icons')),
            ],
        ),
        migrations.CreateModel(
            name='WalletUserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_system', models.CharField(blank=True, max_length=250, null=True)),
                ('d_ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now_add=True)),
                ('d_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.ddevice')),
                ('wallet_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('wallet_user', 'd_device')},
            },
        ),
    ]
