# Generated by Django 5.1.2 on 2024-12-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_ddevice_walletuserdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
