# Generated by Django 5.1.2 on 2024-12-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_emailverificationtoken_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
