# Generated by Django 5.1.2 on 2024-12-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_alter_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
