# Generated by Django 5.1.2 on 2024-12-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='master_password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
