# Generated by Django 5.1.2 on 2024-12-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0011_walletuser_master_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='is_first_oauth_login',
            field=models.BooleanField(default=False),
        ),
    ]
