# Generated by Django 5.1.2 on 2024-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0012_walletuser_is_first_oauth_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='master_password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
