# Generated by Django 5.1.2 on 2024-12-20 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0013_alter_walletuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
