services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "3010:80"
      - "8800:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_USER=main
      - POSTGRES_DB=wallet
      # secrets
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data

  django:
    build:
      context: backend/
      dockerfile: dev.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`localhost`) && (PathPrefix(`/api-v1`) || PathPrefix(`/admin`)))"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    environment:
      - ALLOWED_ORIGINS=http://django:8000,http://localhost:3010
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=heavycream9090@icloud.com
      - DJANGO_SETTINGS_DEBUG_MODE=False
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8000
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_NAME=wallet
      - POSTGRES_DB_USER=main
      - POSTGRES_DB_PORT=5432
      - FRONTEND_URL=http://localhost:3010
      # secrets
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
    command: ["python", "/home/wallet_app/app/entrypoint.py"]
    depends_on:
      - db
    restart: on-failure
    volumes:
      - file_server_data.staticfiles:/home/wallet_app/app/staticfiles
      - file_server_data.images:/home/wallet_app/app/media

  nextjs:
    build:
      context: frontend/
      dockerfile: dev.Dockerfile
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`) && (PathPrefix(`/`) || PathPrefix(`/api`))"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    environment:
      - NEXT_API_URL=http://django:8000
      - NEXTAUTH_URL=http://localhost:3010
      - STATIC_PATH=http://localhost:3010
      # secrets
      - AUTH_TRUST_HOST=false
      - AUTH_SECRET=${SECRET_KEY}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    restart: on-failure
    depends_on:
      - django

  file_server:
    build:
      context: file-server/
      dockerfile: dev.Dockerfile
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.file_server.rule=Host(`localhost`) && PathPrefix(`/backend/static`) || PathPrefix(`/backend/media`)"
    restart: on-failure
    volumes:
      - file_server_data.staticfiles:/home/wallet_app/app/staticfiles
      - file_server_data.images:/home/wallet_app/app/media

volumes:
  postgresdata:
  file_server_data.staticfiles:
  file_server_data.images:
