services:
  updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    networks:
      - ext

  db:
    image: postgres:16
    labels:
      # loadbalancer
      - "traefik.enable=true"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - POSTGRES_USER=main
      - POSTGRES_DB=wallet
      # secrets
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    restart: on-failure
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - ext


  django:
    image: pavelbeard/wallet-backend.production:latest
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`cartera.heavycream.es`) && (PathPrefix(`/api-v1`) || PathPrefix(`/admin`))"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - ALLOWED_ORIGINS=https://cartera.heavycream.es,http://django:8800
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=heavycream9090@icloud.com
      - DJANGO_SETTINGS_DEBUG_MODE=False
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8000
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_NAME=wallet
      - POSTGRES_DB_USER=main
      - POSTGRES_DB_PORT=5432
      - FRONTEND_URL=https://cartera.heavycream.es
      # secrets
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
    depends_on:
      - db
    restart: on-failure
    volumes:
      - file_server_data.staticfiles:/home/wallet_app/app/staticfiles
      - file_server_data.images:/home/wallet_app/app/media
    networks:
      - ext

  nextjs:
    image: pavelbeard/wallet-frontend.production:latest
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`cartera.heavycream.es`) && (PathPrefix(`/`) || PathPrefix(`/api`))"
      - "traefik.http.routers.nextjs.entrypoints=web"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NEXT_API_URL=http://django:8800
      - NEXTAUTH_URL=http://cartera.heavycream.es
      - STATIC_PATH=http://cartera.heavycream.es
      # secrets
      - AUTH_SECRET=${SECRET_KEY}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    restart: on-failure
    depends_on:
      - django
    networks:
      - ext

  file_server:
    image: pavelbeard/wallet-file-server.production:latest
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.file_server.rule=Host(`cartera.heavycream.es`) && (PathPrefix(`/backend/static`) || PathPrefix(`/backend/media`))"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    restart: on-failure
    volumes:
      - file_server_data.staticfiles:/home/wallet_app/app/staticfiles
      - file_server_data.images:/home/wallet_app/app/media
    networks:
      - ext

volumes:
  letsencrypt:
  postgresdata:
  file_server_data.staticfiles:
  file_server_data.images:

networks:
  ext:
    external: true