services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=heavycream9090@icloud.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt

  updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"

  db:
    image: postgres:16
    labels:
      # loadbalancer
      - "traefik.enable=true"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - POSTGRES_USER=main
      - POSTGRES_DB=wallet
      # secrets
      - POSTGRES_PASSWORD=/run/secrets/POSTGRES_DB_PASSWORD_CUSEC
    restart: on-failure
    volumes:
      - postgresdata:/var/lib/postgresql/data


  django:
    image: pavelbeard/wallet-backend.production:latest
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`cusec.es`) && (PathPrefix(`/api-v1`) || PathPrefix(`/admin`))"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - ALLOWED_ORIGINS=https://cusec.es,http://django:8800
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=heavycream9090@icloud.com
      - DJANGO_SETTINGS_DEBUG_MODE=False
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8000
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_NAME=wallet
      - POSTGRES_DB_USER=main
      - POSTGRES_DB_PORT=5432
      - FRONTEND_URL=https://cusec.es
      # secrets
      - SECRET_KEY=/run/secrets/SECRET_KEY_CUSEC
      - AUTH_GOOGLE_ID=/run/secrets/AUTH_GOOGLE_ID_CUSEC
      - AUTH_GOOGLE_SECRET=/run/secrets/AUTH_GOOGLE_SECRET_CUSEC
      - DJANGO_SUPERUSER_PASSWORD=/run/secrets/DJANGO_SUPERUSER_PASSWORD_CUSEC
      - POSTGRES_DB_PASSWORD=/run/secrets/POSTGRES_DB_PASSWORD_CUSEC
      - RESEND_API_KEY=/run/secrets/RESEND_API_KEY_CUSEC
    depends_on:
      - db
    restart: on-failure
    volumes:
      - file_server_data.staticfiles:/home/wallet_app/app/staticfiles
      - file_server_data.images:/home/wallet_app/app/media

  nextjs:
    image: pavelbeard/wallet-frontend.production:latest
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`cusec.es`) && (PathPrefix(`/`) || PathPrefix(`/api`))"
      - "traefik.http.routers.nextjs.entrypoints=web"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - NEXT_API_URL=http://django:8800
      - NEXTAUTH_URL=http://cusec.es
      - STATIC_PATH=http://cusec.es
      # secrets
      - AUTH_SECRET=/run/secrets/SECRET_KEY_CUSEC
      - AUTH_GOOGLE_ID=/run/secrets/AUTH_GOOGLE_ID_CUSEC
      - AUTH_GOOGLE_SECRET=/run/secrets/AUTH_GOOGLE_SECRET_CUSEC
    restart: on-failure
    depends_on:
      - django

  file_server:
    image: pavelbeard/wallet-file-server.production:latest
    labels:
      # loadbalancer
      - "traefik.enable=true"
      - "traefik.http.routers.file_server.rule=Host(`cusec.es`) && (PathPrefix(`/backend/static`) || PathPrefix(`/backend/media`))"
      - "traefik.http.routers.file_server.tls.certresolver=myresolver"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    restart: on-failure
    volumes:
      - file_server_data.staticfiles:/home/wallet_app/app/staticfiles
      - file_server_data.images:/home/wallet_app/app/media

volumes:
  letsencrypt:
  postgresdata:
  file_server_data.staticfiles:
  file_server_data.images:

secrets:
  AUTH_GOOGLE_ID_CUSEC:
    external: true
  AUTH_GOOGLE_SECRET_CUSEC:
    external: true
  SECRET_KEY_CUSEC:
    external: true
  DJANGO_SUPERUSER_PASSWORD_CUSEC:
    external: true
  POSTGRES_DB_PASSWORD_CUSEC:
    external: true
  RESEND_API_KEY_CUSEC:
    external: true