# Generated by Django 5.1.2 on 2024-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecord',
            name='salt',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
