# Generated by Django 5.0.6 on 2024-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
